### PR TITLE
Add some message create

### PR DESCRIPTION
**Pull request by Jerrydotpy**
## Description

Title says it

## Checklist

- [ ] - All code changes have been tested, if any
- [ ] - This PR fixes an already existing issue
- [x] - This PR adds a new feature (new functions, methods, classes, parameters, etc.)
- [ ] - This PR fixes a bug
- [ ] - This PR is a breaking change (removes/renames functions, parameters etc.)
- [ ] - This PR is NOT a code change (changes Documentation files, README.md, CONTRIBUTING.md etc.)
- [ ] - This PR is a code refactor

### CODE REVIEW

**Comment by Jerry-py** [comment]
Close this @TheUntraceable

**Comment by Jerry-py** [comment]
I'll fix it later

**Comment by TheUntraceable** [comment]
> Close this @TheUntraceable

You sure??

**Comment by Jerry-py** [comment]
Yes

**Comment by Jerry-py** [comment]
Because https://github.com/EpikCord/RoboEpik/pull/4 is what tried to do

**Pull request closed without merging**
